[project]
name = "pipeline"
version = "0.1.0"
description = "Virtual enviroment for pipeline project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.0",
    "pyarrow>=23.0.0",
]
